### ISSUE TITLE
LinkRatingExtension: Auch Links zu Personen werden eingefärbt

### ISSUE THREAD

**Issue by VfBFan** [Leinzi/mp-Skripte#2]
Verlinkungen zu Personen (https://www.moviepilot.de/people/…) sollten von der Einfärbung ausgenommen werden.

**Comment by Leinzi** [comment]
Hast du ein Beispiel?

**Comment by VfBFan** [comment]
Ich wollte meinen Beitrag gerade ergänzen. ;-)
Das Problem tritt wohl nur bei der Personenübersicht auf. Also bei Links von Personen zu anderen Personen, z.B. https://www.moviepilot.de/people/wes-anderson.

**Comment by Leinzi** [comment]
Meinst du die Links im Übersichtstext? Die werden nicht von mir eingefärbt. Das ist die Standardlinkfarbe auf Moviepilot. Ich könnte eine andere Farbe für "nicht gesehen" verwenden, dann fällt das eher auf.

**Comment by VfBFan** [comment]
Stimmt ist die Standardfarbe, eine andere Farbe wie z.B. blau wäre echt gut.

**Comment by Leinzi** [comment]
Das Problem sind die unterschiedlichen Designs. Die alten Seiten haben noch eine andere Farbpalette als die im neueren Design (violett/orange/weiß). Ich muss mir eine suchen, die in beiden funktioniert. Das Grün ist bereits eine Abwandlung des Grüns in der mp-Farbpalette. Ich hatte anfangs violett (aus dem Header) probiert, das ist aber nicht aufgefallen.

**Comment by VfBFan** [comment]
Die Farbe bezgl. den Filmlinks würde ich so lassen. Ich würde nur die Farbe von den Personenlinks in der Übersichtsseite ändern. Das Blau vom Dashboard bzw. Cockpit würde passen.
![Zwischenablage01](https://user-images.githubusercontent.com/39465826/84496888-0bc57b80-acae-11ea-93fb-3569d69022dc.jpg)

**Comment by Leinzi** [comment]
Ach, so meinst du. Das ist dann aber unter Umständen nicht so langlebig, da das Redesign über kurz oder lang alle Bereiche auf moviepilot betreffen wird. Spätestens dann müsste ich das bei mir wieder anpassen. Ich beschränke das jetzt erstmal nur auf die people-Route.

**Comment by Leinzi** [comment]
Schau mal, ob 0.1.2 passt. Mir sind die Personenlinks ehrlich gesagt etwas zu dunkel, aber ich weiß gerade nicht, wie ich das verbessern könnte - höchstens noch bold.

**Comment by VfBFan** [comment]
Passt erstmal, trotz etwas dunklem blau. Ich danke dir.

**Comment by Leinzi** [comment]
Ich hatte erst #2d2338 versucht, das ist die Linkfarbe auf dem Dashboard, aber das hebt sich noch weniger von der Textfarbe (schwarz) ab. Hatte es daher etwas heller gemacht und den Hovereffekt hinzugefügt. Außerdem habe ich mich nur auf die Personenbeschreibung beschränkt, da sonst alle anderen Links seltsam ausgesehen hätten.
