### ISSUE TITLE
Rubrikenauswahl "Weitere Artikel" hat keine Funktion mehr

### ISSUE THREAD

**Issue by VfBFan** [Leinzi/mp-Skripte#3]
mp-movies-cleanup.user.js & mp-series-cleanup.user.js:

Aufgrund von Änderungen an der Bezeichnung der Rubrikenüberschrift seitens Moviepilot funktioniert der entsprechende Filter "Weitere Artikel" nicht mehr.
Die Überschriften auf den Film- bzw. Serienseiten heißen nun "WEITERE FILM-NEWS" und "WEITERE SERIEN-NEWS".

**Comment by Leinzi** [comment]
Hi,

"Weitere Artikel" hat auf eine andere Rubrik gezielt, die nur ohne Adblocker sichtbar ist. Das waren diese hässlichen Outbrain-News. Diese entferne ich nun ohne Checkbox. Des weiteren entferne ich den Videoplayer im Footer ungefragt.

Ich glaube, ich wollte ein Element zwischen den Kommentaren und dem Footer behalten, da damals die aufgeklappten Likes hinter dem Footer-Element verschwunden waren, wenn es mehr als 4 Likes unter dem letzten Kommentar gab.

Die Checkbox "Weitere Artikel" zielt nun auf "WEITERE FILM-NEWS" bzw. "WEITERE SERIEN-NEWS" ab und sollte nun funktionieren.

**Comment by VfBFan** [comment]
Perfekt, funktioniert jetzt wie erwartet.
Vielen Dank.

PS: Dein Skript mit den angepassten Fonts macht das Lesen auch wieder echt angenehm.

**Comment by Leinzi** [comment]
Das war nur auf die Schnelle hingehackt und setzt einfach die Klassen, die die Originalfonts aktivieren. Also das, was passiert, wenn alle Cookies akzeptiert werden.

Ich verstehe den Ansatz, den moviepilot hier verfolgt, nicht wirklich, denn Schriftarten gehören für mich zur Basis und sollten niemandem verwehrt werden.
